-- Haskell module generated by the BNF converter

module SkelCalc where

import qualified AbsCalc

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transProgram :: AbsCalc.Program -> Result
transProgram x = case x of
  AbsCalc.EAdd program exp -> failure x
  AbsCalc.ESub program exp -> failure x
transExp :: AbsCalc.Exp -> Result
transExp x = case x of
  AbsCalc.EMul exp1 exp2 -> failure x
  AbsCalc.EDiv exp1 exp2 -> failure x
  AbsCalc.EInt integer -> failure x

