{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for CMM.
--   Generated by the BNF converter.

module CMM.Print where

import qualified CMM.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print CMM.Abs.Id where
  prt _ (CMM.Abs.Id i) = doc $ showString $ i
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print CMM.Abs.Program where
  prt i e = case e of
    CMM.Abs.PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print CMM.Abs.Def where
  prt i e = case e of
    CMM.Abs.DFun type_ id args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [CMM.Abs.Def] where
  prt = prtList

instance Print CMM.Abs.Arg where
  prt i e = case e of
    CMM.Abs.ADecl type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [CMM.Abs.Arg] where
  prt = prtList

instance Print CMM.Abs.Stm where
  prt i e = case e of
    CMM.Abs.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    CMM.Abs.SDecls type_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 ids, doc (showString ";")])
    CMM.Abs.SInit type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    CMM.Abs.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    CMM.Abs.SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    CMM.Abs.SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    CMM.Abs.SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [CMM.Abs.Stm] where
  prt = prtList

instance Print CMM.Abs.Exp where
  prt i e = case e of
    CMM.Abs.EBool boollit -> prPrec i 6 (concatD [prt 0 boollit])
    CMM.Abs.EInt n -> prPrec i 6 (concatD [prt 0 n])
    CMM.Abs.EDouble d -> prPrec i 6 (concatD [prt 0 d])
    CMM.Abs.EId id -> prPrec i 6 (concatD [prt 0 id])
    CMM.Abs.EApp id exps -> prPrec i 6 (concatD [prt 0 id, doc (showString "("), prt 0 exps, doc (showString ")")])
    CMM.Abs.EPost id incdecop -> prPrec i 6 (concatD [prt 0 id, prt 0 incdecop])
    CMM.Abs.EPre incdecop id -> prPrec i 6 (concatD [prt 0 incdecop, prt 0 id])
    CMM.Abs.EMul exp1 mulop exp2 -> prPrec i 5 (concatD [prt 5 exp1, prt 0 mulop, prt 6 exp2])
    CMM.Abs.EAdd exp1 addop exp2 -> prPrec i 4 (concatD [prt 4 exp1, prt 0 addop, prt 5 exp2])
    CMM.Abs.ECmp exp1 cmpop exp2 -> prPrec i 3 (concatD [prt 4 exp1, prt 0 cmpop, prt 4 exp2])
    CMM.Abs.EAnd exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "&&"), prt 3 exp2])
    CMM.Abs.EOr exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "||"), prt 2 exp2])
    CMM.Abs.EAss id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 exp])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [CMM.Abs.Exp] where
  prt = prtList

instance Print CMM.Abs.IncDecOp where
  prt i e = case e of
    CMM.Abs.OInc -> prPrec i 0 (concatD [doc (showString "++")])
    CMM.Abs.ODec -> prPrec i 0 (concatD [doc (showString "--")])

instance Print CMM.Abs.MulOp where
  prt i e = case e of
    CMM.Abs.OTimes -> prPrec i 0 (concatD [doc (showString "*")])
    CMM.Abs.ODiv -> prPrec i 0 (concatD [doc (showString "/")])

instance Print CMM.Abs.AddOp where
  prt i e = case e of
    CMM.Abs.OPlus -> prPrec i 0 (concatD [doc (showString "+")])
    CMM.Abs.OMinus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print CMM.Abs.CmpOp where
  prt i e = case e of
    CMM.Abs.OLt -> prPrec i 0 (concatD [doc (showString "<")])
    CMM.Abs.OGt -> prPrec i 0 (concatD [doc (showString ">")])
    CMM.Abs.OLtEq -> prPrec i 0 (concatD [doc (showString "<=")])
    CMM.Abs.OGtEq -> prPrec i 0 (concatD [doc (showString ">=")])
    CMM.Abs.OEq -> prPrec i 0 (concatD [doc (showString "==")])
    CMM.Abs.ONEq -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print CMM.Abs.BoolLit where
  prt i e = case e of
    CMM.Abs.LTrue -> prPrec i 0 (concatD [doc (showString "true")])
    CMM.Abs.LFalse -> prPrec i 0 (concatD [doc (showString "false")])

instance Print CMM.Abs.Type where
  prt i e = case e of
    CMM.Abs.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    CMM.Abs.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    CMM.Abs.Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    CMM.Abs.Type_void -> prPrec i 0 (concatD [doc (showString "void")])

instance Print [CMM.Abs.Id] where
  prt = prtList

