name: make

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          cabal install happy
          cabal install alex
          cabal install BNFC
      - name: Run Build
        run: make
      - name: Run Test
        run: make test